services:
  notice-service:
    build: ./notice-service
    environment:
      PORT: 5001
    ports:
      - "5001:5001"

  auth-service:
    build: ./auth-service
    environment:
      PORT: 5002
    ports:
      - "5002:5002"

  gateway:
    build: ./gateway
    environment:
      PORT: 5003
      NOTICE_SERVICE_URL: http://notice-service:5001
      AUTH_SERVICE_URL: http://auth-service:5002
    ports:
      - "5003:5003"
    depends_on:
      - notice-service
      - auth-service

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:5003
    ports:
      - "3000:3000"
    depends_on:
      - gateway
